# Generated by Django 5.1.1 on 2024-10-06 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("moviesite", "0002_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="types",
        ),
    ]
