# Generated by Django 5.1.1 on 2024-10-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moviesite", "0003_remove_movie_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="types",
            field=models.CharField(
                blank=True,
                choices=[
                    ("144", "144"),
                    ("360", "360"),
                    ("480", "480"),
                    ("720", "720"),
                    ("1080", "1080"),
                ],
                default="360",
                max_length=10,
                null=True,
            ),
        ),
    ]
