# Generated by Django 5.1.1 on 2024-10-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moviesite", "0004_movie_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.DateField(),
        ),
    ]
